dataflor-ag/webstyleguide

packages/df-ui-theme/src/sandbox/ui.tsx, packages/df-ui-theme/src/theme/components.tsx
- adjust default container size and padding
=> style: adjust app- and toolbar appearance

packages/df-ui-theme/src/theme/components.tsx, packages/df-ui-theme/src/theme/shape.tsx
- adjust radius for various components
=> style: optimize use of radius for components

packages/df-ui-theme/src/theme/components.tsx, packages/df-ui-theme/src/theme/shadows.tsx
- adjust primary focus shadow
- adjust dialog backdrop
=> style: optimize colors

packages/df-ui-theme/src/sandbox/ui.tsx, packages/df-ui-theme/src/theme/components.tsx
=> style: adjust tab appearance

packages/df-ui-theme/src/sandbox/ui.tsx, packages/df-ui-theme/src/theme/components.tsx
- adjust menu divider
- optimize select font size
=> style: adjust dropdown / menu appearance

stories/examples/Pages.stories.tsx
- add login
- add project (empty state)
=> feat: add stories for examples pages

packages/df-ui-theme/src/sandbox/ui.tsx, packages/df-ui-theme/src/theme/components.tsx
- show placeholders for inputs
- adjust placeholder color for selects
=> style: adjust placeholder appearance

packages/df-ui-theme/index.html, packages/df-ui-theme/src/sandbox/ui.tsx, packages/df-ui-theme/src/theme/components.tsx, packages/df-ui-theme/src/theme/utils/chips.tsx
=> style: add chips

packages/df-ui-theme/src/theme/components/form.ts, packages/df-ui-theme/src/theme/components/select.ts
=> style: adjust defaultProps

packages/df-ui-theme/src/theme/components/button.ts, stories/mui/Button.stories.tsx
- adjust colors for icon
- adjust disabled colors
=> style: adjust button with icon appearance

packages/df-ui-theme/src/theme/components/form.ts, stories/mui/Input.stories.tsx
- adjust sizes
- adjust endIcon color
=> style: adjust input with icon appearance

packages/df-ui-drawer/lib/Drawer/DrawerHeader.tsx, stories/examples/Components.stories.tsx
- adjust close button appearance
=> style: add close button to drawer

packages/df-ui-icons/lib/icons/closeSmall.tsx, packages/df-ui-icons/lib/icons/index.ts, packages/df-ui-theme/src/theme/components/chip.ts, packages/df-ui-theme/src/theme/utils/chips.tsx, stories/mui/Chip.stories.tsx
- add examples with icon
- optimize close icon
- optimize size and padding for badges
=> style: adjust badge/chip appearance

package-lock.json
Dependencies should now be ok.
=> CLOUD-1303 package-lock.json was out of sync with package.json

package-lock.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/pagination.ts
-  increased highlighting of current page in pagination
=> [CLOUD-1358-Projekt-bersicht-Paginierung-berarbeiten]

package-lock.json, packages/df-ui-dialog-create-edit/lib/DialogCreateEdit/DialogCreateEdit.tsx, packages/df-ui-dialog-create-edit/package.json
=> [adjust-create-edit-dialog] 

package-lock.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/button.ts, packages/df-ui-theme/src/components/chip.ts, packages/df-ui-theme/src/icons/chips.tsx, stories/mui/Button.stories.tsx
- added more button designs (outlined primary, text primary, text error)
- adjusted delete-icon on chip-component
=> Add primary colored text button

package-lock.json, packages/df-ui-dialog-delete/.eslintrc.cjs, packages/df-ui-dialog-delete/.gitignore, packages/df-ui-dialog-delete/README.md, packages/df-ui-dialog-delete/lib/DialogDelete/DialogDelete.tsx, packages/df-ui-dialog-delete/lib/DialogDelete/index.ts, packages/df-ui-dialog-delete/lib/index.ts, packages/df-ui-dialog-delete/package.json, packages/df-ui-dialog-delete/prettierrc.json, packages/df-ui-dialog-delete/tsconfig.json, packages/df-ui-dialog-delete/vite.config.ts, packages/df-ui-dialog-header/lib/DialogHeader/DialogHeader.tsx, packages/df-ui-dialog-header/package.json, packages/df-ui-icon-wrapper/lib/IconWrapper/IconWrapper.tsx, packages/df-ui-icon-wrapper/package.json, stories/components/DialogDelete.stories.tsx
- added custom delete dialog component with optional slots for two text paragraphs and a warning box (and optional custom child content)
=> Create delete dialog component

package-lock.json, packages/df-ui-dialog-delete/lib/DialogDelete/DialogDelete.tsx, packages/df-ui-dialog-delete/package.json, packages/df-ui-dialog-header/lib/DialogHeader/DialogHeader.tsx, packages/df-ui-dialog-header/package.json, packages/df-ui-page-header/lib/PageHeader/PageHeader.tsx, packages/df-ui-page-header/package.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/menu.ts, stories/components/DialogDelete.stories.tsx, stories/components/PageHeader.stories.tsx
-  added tabMenu-prop to page header
-  adjusted minWidth of menuitem to prevent wrong height of items with font-sizes under 16px
=> [adjust-page-header-padding-for-tab-content]

package-lock.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/checkbox.ts, packages/df-ui-theme/src/components/radio.ts, stories/mui/Form.stories.tsx
- added primary colored checkboxes and radio elements
=> Primary colored checkboxes and radios

package-lock.json, packages/df-ui-page-header/lib/PageHeader/PageHeader.tsx, packages/df-ui-page-header/package.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/checkbox.ts, packages/df-ui-theme/src/components/radio.ts, packages/df-ui-theme/src/components/switchToggle.ts, stories/mui/Form.stories.tsx
- primary colored checkboxes and radios are now the default
- checkboxes for table-rows are now also primary-colored
- changed toggle-switches to primary colored
- adjusted top-padding of page header component
=> Primary colored checkboxes in tables

package-lock.json, packages/df-ui-downloadbox/lib/Downloadbox/Downloadbox.tsx, packages/df-ui-downloadbox/package.json, stories/components/Downloadbox.stories.tsx
- added optional tooltip and maxwidth to downloadbox file title
=> Adjust download box

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json
-  fixed account data clickhandler
-  adjusted slotinfo styling
=> Appbar adjustments

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, packages/df-ui-uploadbox/.eslintrc.cjs, packages/df-ui-uploadbox/.gitignore, packages/df-ui-uploadbox/README.md, packages/df-ui-uploadbox/lib/Uploadbox/ColorMapping.ts, packages/df-ui-uploadbox/lib/Uploadbox/Uploadbox.tsx, packages/df-ui-uploadbox/lib/Uploadbox/index.ts, packages/df-ui-uploadbox/lib/index.ts, packages/df-ui-uploadbox/package.json, packages/df-ui-uploadbox/tsconfig.json, packages/df-ui-uploadbox/vite.config.ts, stories/components/CustomAppBar.stories.tsx, stories/components/Uploadbox.stories.tsx
- Add uploadbox component with upload progress bar
- added ID to account menu button
=> Add uploadbox component

.github/workflows/deploy.yml, package-lock.json, packages/df-ui-blazorinterop/lib/CustomAppBar/CustomAppBarInterop.tsx, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/avatar.ts, stories/components/CustomAppBar.stories.tsx, stories/mui/Avatar.stories.tsx
- added company menu to custom appbar
- added rounded square variant to avatar
- adjusted interop to work with changes in custom appbar
=> Cloud 1800 header firmenavatar hinzuf gen

packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, stories/components/CustomAppBar.stories.tsx
- company logo no longer shows user icon as fallback
=> [adjust-company-logo-in-appbar] 

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, packages/df-ui-dashboard/package.json, packages/df-ui-dialog-create-edit/package.json, packages/df-ui-dialog-delete/package.json, packages/df-ui-dialog-header/package.json, packages/df-ui-icons/package.json, packages/df-ui-theme/package.json, stories/components/CustomAppBar.stories.tsx
- adjusted avatar logo to show initals if img url is empty string
- updated versions
=> Adjust company logo in appbar fix

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/package.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/stepper.ts
- adjusted color of completed step icon
=> Adjust stepper

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, stories/components/CustomAppBar.stories.tsx
- icon variant of avatar/logo is always shown if avatar/logo has no image url
=> Custom appbar remove initals from avatar and logo

package-lock.json, packages/df-ui-image-selector/lib/ImageSelector/ImageSelector.tsx, packages/df-ui-image-selector/package.json, stories/components/ImageSelector.stories.tsx
image selector button is now customizable
=> [add-customizable-button-to-image-selector] 

package-lock.json, packages/df-ui-dialog-create-edit/lib/DialogCreateEdit/DialogCreateEdit.tsx, packages/df-ui-dialog-create-edit/package.json, packages/df-ui-dialog-delete/lib/DialogDelete/DialogDelete.tsx, packages/df-ui-dialog-delete/package.json
Add customizable icons for save and delete buttons in dialog components
=> Cloud-2056-Buttons-additionally-provided-with-icons-undone-buttons

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, packages/df-ui-theme/package.json, packages/df-ui-theme/src/components/container.ts, stories/components/CustomAppBar.stories.tsx
- adjusted custom appbar width
- adjusted slotinfo chip
- adjusted container width in theme
=> [adjust-container-width] 

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json
=> Add padding to appbar

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, stories/components/CustomAppBar.stories.tsx
- divider between company and account menu is now also shown if no other buttons are rendered
=> Fix appbar divider

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, packages/df-ui-dialog-create-edit/lib/DialogCreateEdit/DialogCreateEdit.tsx, packages/df-ui-dialog-create-edit/package.json, packages/df-ui-dialog-delete/lib/DialogDelete/DialogDelete.tsx, packages/df-ui-dialog-delete/package.json, packages/df-ui-dialog-header/lib/DialogHeader/DialogHeader.tsx, packages/df-ui-dialog-header/package.json, packages/df-ui-uploadbox/lib/Uploadbox/Uploadbox.tsx, packages/df-ui-uploadbox/package.json
- defined variants/colors of elements
- made create dialog icon size responsive
=> [define-styling-variants] 

package-lock.json, packages/df-ui-blazorinterop/lib/CustomAppBar/CustomAppBarInterop.tsx, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, stories/components/CustomAppBar.stories.tsx
- language menu now closes after clicking on a menu item
- added language menu functions to interop
=> Cloud 2195 language menu schlie t nicht

package-lock.json
=> [packagagelock-fix] 

MAINTAINER.md, README.md, package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, stories/components/CustomAppBar.stories.tsx
- added optional language flag as language menu icon
- language menu now closes when clicking on backdrop
- moved instruction for updating packages to maintainer-readme (other readme changes are just formatting)
=> Cloud 2209 icon language selector

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, packages/df-ui-dialog-create-edit/lib/DialogCreateEdit/DialogCreateEdit.tsx, packages/df-ui-dialog-create-edit/package.json, packages/df-ui-dialog-delete/lib/DialogDelete/DialogDelete.tsx, packages/df-ui-dialog-delete/package.json, packages/df-ui-dialog-header/lib/DialogHeader/DialogHeader.tsx, packages/df-ui-dialog-header/package.json, packages/df-ui-downloadbox/lib/Downloadbox/Downloadbox.tsx, packages/df-ui-downloadbox/package.json, packages/df-ui-image-selector/lib/ImageSelector/ImageSelector.tsx, packages/df-ui-image-selector/package.json
=> Cloud 2280 webstyleguide adjust appbar to improve handling in tests

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, stories/components/CustomAppBar.stories.tsx
- adjusted language selector menu
=> Cloud 2293 language selector anpassungen

package-lock.json, packages/df-ui-blazorinterop/lib/CustomAppBar/CustomAppBarInterop.tsx, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json
- added device management menu item
=> Cloud 2326 webstyleguide menu um gerateverwaltung erweitern

.storybook/main.js, package-lock.json, package.json
Update Storybook and related dependencies to the latest minor version, simplifying the Storybook configuration by removing the getAbsolutePath function
=> Upgrade Storybook to version 8.6.2

package-lock.json, packages/df-ui-blazorinterop/package.json, packages/df-ui-custom-app-bar/lib/CustomAppBar/CustomAppBar.tsx, packages/df-ui-custom-app-bar/package.json, packages/df-ui-dialog-create-edit/lib/DialogCreateEdit/DialogCreateEdit.tsx, packages/df-ui-dialog-create-edit/package.json, stories/components/CustomAppBar.stories.tsx
- made button actions and texts optional
- adjusted slotinfo in appbar
=> Adjust create edit dialog buttons
